services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
